### ISSUE TITLE
Combining problem with glyph ◌ (25CC), and two proposals

### ISSUE THREAD

**Issue by theblursed** [Tosche/Alcarin-Tengwar#11]
Dear Tosche,
I first came in contact with your Alcarin font some time ago, but it’s only since I’ve recently began getting more seriously interested in tengwar that I actually noticed how good its design is. In my opinion, it’s easily the best tengwar font out now, for overall readability, elegance and functionaly. Well done.

I’m writing you now for some issues and proposals.

1. There seems to be a combining problem with glyph ◌ (`25CC`). In LibreOffice, it does not combine correctly (the combining characters “fall”) unless it is preceded by a tengwar character or another ◌, then it combines correctly. However, it combines correctly when it is the first character in a paragraph. See pictures:

![Schermata 2023-06-15 alle 11 18 29](https://github.com/Tosche/Alcarin-Tengwar/assets/134559730/bf67355f-f8d9-4e75-abab-2945f626facc)

I have not done an extensive testing to see whether there are other conditions implied.

2. This is not a “problem”, but rather a matter of estethical opinion. In the  ligature (`E024` + `E050`), the top horizontal bar seems too high to me, and it's a lot higher than on other letters. In my opinion, this is not good looking and appears inconsistent, and especially stands out in small size text:

![Schermata 2023-06-15 alle 11 21 41](https://github.com/Tosche/Alcarin-Tengwar/assets/134559730/a2758705-493d-41c3-ba38-b34b07705c38)

Would it be possible to have it a bit lower, at the same height it is on other letters, maybe even touching the letter, consistently with what it does with the other ones? See a comparison with Telcontar:

![Schermata 2023-06-15 alle 11 22 47](https://github.com/Tosche/Alcarin-Tengwar/assets/134559730/63419ff3-06c7-483b-bfca-bff3f0faad42)

3. As an inquiry (as this is for a non-standard use of tengwar), would you consider the possibility of having the diacritics to combine also with “punctuation” characters as , ,  (`E060`, `E061`, `E062`)? I’m not an expert of fonts and typography, but I think it would need just the addition of anchor points to the glyphs to work?
A possible outcome:
![Schermata 2023-06-15 alle 11 30 30](https://github.com/Tosche/Alcarin-Tengwar/assets/134559730/23c2e4c7-ada4-4983-b331-17b917b3d0ae)
Thank you for all your beautiful work! Keep up the good job.

**Comment by Tosche** [comment]
Thanks for your kind comments! And apologies for the late reply.

1. Dotted circle. in OpenOffice: I think it's the issue with the app as I cannot recreate it elsewhere including my OpenOffice, 4.1.14 on Mac.
2. Lowered the macron height to the same level as the others. I decided to not let it touch the letters unlike in Telcontar; Because of Alcarin's shorter ascender, the attached macron looked like a flag.
3. Done.

**Comment by theblursed** [comment]
You have nothing to apologize for! Thank you very much.

1. Understood. It's not a big issue for me as I don't need to use the glyph a lot, so I'll just use some custom solutions.
2. Good, I like it a lot more now.
3. Thank you again! 🙂
