### ISSUE TITLE
Missing punctuation marks

### ISSUE THREAD

**Issue by skalyan91** [Tosche/Alcarin-Tengwar#2]
Congratulations on all the effort required to create such a full-featured font! Unfortunately, at least a couple of punctuation marks are missing, despite being accessible from the (relevant parts of the) keyboard map: ⁘ and ⸭.

**Comment by Tosche** [comment]
I've checked the keyboard mapping, and it was using standard code points (u+2058 ⁘ and u+205B ⁛). The font contain both but in PUA mapping which I based on Free Tengwar's. It's not complete as it lacks the PUA counterpart of four square dots (u+E2EC ⸬). I think I should revise the keyboard mapping, and double-encode the punctuations just to be safe.

**Comment by skalyan91** [comment]
Now ⁘ and ⁝ work, but ⸭ still shows up in a different font.

**Comment by Tosche** [comment]
Updated both font and keyboard

**Comment by skalyan91** [comment]
This issue has been fixed. Thanks!
