### ISSUE TITLE
Letter shape/kerning suggestions

### ISSUE THREAD

**Issue by skalyan91** [Tosche/Alcarin-Tengwar#3]
1. At text sizes, the _s_-tengwar ( and ) look too narrow compared to the bowl-and-stem letters. See Telcontar for a good reference. (There may be a similar issue with the _z_-tengwar, though I haven’t tested these yet.) At large sizes these letters look fine, so I suspect this may be a result of the font having been designed at a larger size than the one it’s meant to be used at.
2. The _o_- and _u_-tehtar look too “flat” to me; for both readability and style reasons, I think they should be more rounded. Again, see Telcontar (though I understand that some adjustments needed to be made when going from a calligraphic style to a “Transitional” style).
3. Not lettershape-related _per se_, but hinting definitely needs to be improved (even in the OTF version): at text sizes, the thickness of stems varies haphazardly, and this significantly impacts readability.
4. Ideally, when a vowel carrier with tehta precedes a letter with an ascender on the left, the two letters should be spaced further apart, to visually accommodate the tehta. (There are analogous situations in Latin text, e.g. combinations such as íh and íl, but as far as I’m aware no font deals with this issue.)

**Comment by Tosche** [comment]
Thanks! I've just updated the font, hopefully addressing the first two.
Regarding 3, I noticed that the horizontal hinting seems to be failing, but I am not sure if that's what you're seeing. Could you send me a screenshot?
The 4th one may take a bit of time but will be done.

**Comment by skalyan91** [comment]
Thanks! The _s_-tengwar look better than before, but are still too “weak” in my opinion. I think the issue is that the ascender/descender is exactly parallel to the nib angle, and so tends to “vanish” at text sizes. Telcontar addresses this issue by making the ascender/descender slightly steeper than the nib angle.

The shapes of the tehtar look much better now.

For 3, here is a screenshot from `War of the Ring.pdf`:

![Screen Shot 2022-01-06 at 9 30 32 am](https://user-images.githubusercontent.com/2990272/148304501-a903f8d9-061e-4189-b946-75da09a39818.png)

Note how in the first line, the stem of the first “the” is noticeably thinner than that of the second “the”.

I think 4 is somewhat addressed by the improvements to the shapes of the tehtar.

**Comment by Tosche** [comment]
I presume you're talking about silme? I've made the stroke a bit thicker now.

This screenshot is from Mac, right? The hinting is actually not used on Mac, so this is not a demonstration of hinting issue. Then again, I am not clear on what you see.

**Comment by skalyan91** [comment]
Yes, I meant _silme_ (sorry, I’m not very familiar with the names of the letters). Thanks!

Yes, the screenshot is from Mac. Oh well, I’ll try to ignore the hinting issues, then.

**Comment by skalyan91** [comment]
_Silme_ is definitely looking better than before, but still seems a bit off. I think what I’m reacting to is that it seems to have a smaller x-height than the other letters, as well as a smaller counter. Once again, the shape used in Telcontar doesn’t have this issue.

**Comment by Tosche** [comment]
I'm not sure if Telcontar's silme is aligning at x-height better; it's not that different in my opinion, if not worse. It has a more upright posture partially thanks to the thicker terminal at the ascender that's curling back. Ultimately I think my design is not a dealbreaker in terms of functionality or legibility, and it seems to be a matter of taste at this point. I might update this in the future, but the priority is low.

**Comment by skalyan91** [comment]
Fair enough. Maybe I’m just using Alcarin at too small a size. I’ll mark this issue as “closed”.

(By the way, I’m looking at the font on a Linux computer, and the hinting is beautiful! It must be a Mac-specific issue, then.)
