### ISSUE TITLE
Review RFNs

### ISSUE THREAD

**Issue by davelab6** [Tosche/Alcarin-Tengwar#4]
https://github.com/Tosche/Alcarin-Tengwar/blob/7120d4ebb71534fbcce0c3205b78498f45ed397c/OFL.txt#L2 doesn't include the family name which is odd. 

Perhaps the RFNs should be Alcarin and Toshi and Tosche (ie trademarks and names other people shouldn't use without permission) -- but *not* tengwar, since that prohibits any downstream user from using that in the name

**Comment by Tosche** [comment]
Thanks! That was the name before I decided on Alcarin. I've updated the text.
