### ISSUE TITLE
Tehtar collisions

### ISSUE THREAD

**Issue by skalyan91** [Tosche/Alcarin-Tengwar#6]
![Screen Shot 2022-01-15 at 9 12 13 pm](https://user-images.githubusercontent.com/2990272/149619618-5da0684c-4167-4956-aa88-788c90f961b8.png)

I know I mentioned this in a previous issue in the context of possibly adjusting the kerning, but maybe a simpler (and more consistent) solution would be to make the _o_- and _u_-tehtar more vertical?

**Comment by Tosche** [comment]
Sorry to get back on this. I've added contextual kernings for this kind of combinations.
